name: LLM Code Review

on:
  pull_request:
    types: [opened, synchronize]

# Updated permissions block
permissions:
  contents: read
  pull-requests: write
  issues: write
  metadata: read    # Add this for repository metadata access
  statuses: write   # Add this for status updates

jobs:
  review:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run code review
        env:
          # Use GITHUB_TOKEN differently
          GIT_TOKEN: ${{ github.token }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python main.py ${{ github.event.pull_request.number }}