name: LLM Code Review

on:
  pull_request:
    types: [opened, synchronize]

# Explicitly declare token permissions
permissions:
  contents: read
  pull-requests: write
  issues: write      # Add this if you're commenting on PRs
  actions: read      # Add this for workflow access

jobs:
  review:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Explicitly use token for checkout
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Debug Token
        run: |
          echo "Token starts with: ${GIT_TOKEN:0:4}..."
          echo "Repository: ${{ github.repository }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
        env:
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run code review
        env:
          GIT_TOKEN: ${{ github.token }}  # Use github.token instead of secrets.GITHUB_TOKEN
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python main.py ${{ github.event.pull_request.number }}