name: LLM Code Review

on:
  pull_request:
    types: [opened, synchronize]

# Correct permissions block
permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: write
  checks: write     # Add this for check runs
  id-token: write   # Add this for token authentication

jobs:
  review:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Debug Token
        run: |
          echo "Running with token starting with: ${GIT_TOKEN:0:4}..."
          echo "Repository: ${{ github.repository }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
        env:
          GIT_TOKEN: ${{ github.token }}
      
      - name: Run code review
        env:
          GIT_TOKEN: ${{ github.token }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python main.py ${{ github.event.pull_request.number }}